<?php

namespace Xali\Bundle\UserBundle\Entity;

use Xali\Bundle\CampBundle\Entity\Camp;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Update the user's camp
     * 
     * @param \Xali\Bundle\UserBundle\Entity\User $volunteer
     * @param \Xali\Bundle\CampBundle\Entity\Camp $camp
     * @return integer -1 if parameters type are invalid, 0 if request failed
     * and 1 else
     */
    public function updateCamp($volunteer, $camp) {
        $return = 0;
        //If parameters are invalids (usually $volunteer)
        if ($volunteer instanceof User && $camp instanceof Camp) {
            $queryBuilder = $this->createQueryBuilder('u');
            $q = $queryBuilder->update('XaliUserBundle:User', 'u')
                         ->set('u.camp', ':camp')
                         ->setParameter('camp', $camp)
                         ->where('u.id = :user_id')
                         ->setParameter('user_id', $volunteer->getId())
                         ->getQuery()
                    ;
            $return = $q->execute();
        } else {
            $return = -1;
        }
        return $return;
    }
    
    /**
     * Find a user, joined with its camp
     * 
     * @param integer $id
     * @return Xali\Bundle\UserBundle\Entity\User
     * @author Anthony Bocci <boccianthony@yahoo.fr>
     */
    public function findWithCamp($id)
    {
        return $queryBuilder = $this->createQueryBuilder('u')
                     ->where('u.id = :user_id')
                     ->setParameter('user_id', $id)
                     ->leftJoin('u.camp', 'c')
                     ->addSelect('c')
                     ->getQuery()
                     ->getOneOrNullResult();
    }
}
