#Add organisation
xali_organisation_add_organisation:
    path:     /add_organisation
    defaults: { _controller: XaliOrganisationBundle:Organisation:add_organisation }

#Update organisation
xali_organisation_update_organisation:
    path:     /update_organisation
    defaults: { _controller: XaliOrganisationBundle:Organisation:update_organisation }

#See profile. Add an *obligatory* id after /profile
xali_organisation_profile:
    path:     /profile
    defaults: { _controller: XaliOrganisationBundle:Organisation:profile }