xali_user:
    resource: "@XaliUserBundle/Resources/config/routing.yml"
    prefix:   /user

xali_camp:
    resource: "@XaliCampBundle/Resources/config/routing.yml"
    prefix:   /camp

xali_organisation:
    resource: "@XaliOrganisationBundle/Resources/config/routing.yml"
    prefix:   /organisation

xali_survivor:
    resource: "@XaliSurvivorBundle/Resources/config/routing.yml"
    prefix:   /survivor

xali_default:
    resource: "@XaliDefaultBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller: XaliUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:  
    pattern: /logout

app:
    resource: @AppBundle/Controller/
    type:     annotation
