# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Xali\Bundle\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 9616
            encode_as_base64: true

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_VOLUNTEER, ROLE_ORGANISATION]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity: { class: Xali\Bundle\UserBundle\Entity\User, property: username }


    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        #Allow user to access to welcome page and login page even if he's anonymous
       # welcome_login:
        #    pattern:    ^/(login)?$
         #   anonymous:  true
            
        main:
            pattern:    ^/
            anonymous: true
            #Update to false to secure all URLs
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   logout
                target: /
            remember_me:
                key:    %secret%
            
            
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }