## YAML Template.
---
#Add a volunteer
xali_user_registration_register:
    path:   /register
    defaults: { _controller: XaliUserBundle:Registration:register }
    
#Show profile
xali_user_profile_show:
    path:   /user/profile/{id_user}
    defaults: { _controller: XaliUserBundle:Profile:show }
    requirements:
        id_user:    \d+
    
#Edit profile
xali_user_profile_edit:
    path:   /user/profile/edit/{id}
    defaults: { _controller: XaliUserBundle:Profile:edit }
    
