#XaliRightsManager manage rights, verify if a user can add a survivor in a camp
# or if he belong to an organisation, etc
services:
    xali_user.rightsmanager:
        class: Xali\Bundle\UserBundle\RightsManager\XaliRightsManager
        #arguments:
        #     entityManager: "@doctrine.orm.entity_manager"
