#Add and update a survivor in the camp which has the id {id}
#To update a survivor we give its id {survivor_id}
xali_survivor_management_add_survivor:
    path:     /{id}/add_survivor/{survivor_id}
    defaults: { _controller: XaliSurvivorBundle:Survivor:add_survivor, survivor_id: 0 }
    requirements:
        id: \d+
        survivor_id: (\d+)

#Add an *obligatory* id after /profile
xali_survivor_profile_profile:
    path:     /profile/{id}
    defaults: { _controller: XaliSurvivorBundle:Survivor:see_profile }

#Search a survivor
xali_survivor_search_search:
    path:     /search
    defaults: { _controller: XaliSurvivorBundle:Survivor:search }