#Add and update a survivor in the camp which has the id {id}
#To update a survivor we give its id {survivor_id}
xali_survivor_management_add_survivor:
    path:     /{id}/add_survivor/{survivor_id}
    defaults: { _controller: XaliSurvivorBundle:Survivor:add_survivor, survivor_id: 0 }
    requirements:
        id: \d+
        survivor_id: (\d+)

#See survivor's profile
xali_survivor_profile_profile:
    path:     /profile/{id}
    defaults: { _controller: XaliSurvivorBundle:Survivor:see_profile }

#If a survivor leave a camp
xali_survivor_management_leave_camp:
    path:       /{survivor_id}/leave_camp/{camp_id}
    defaults:   { _controller: XaliSurvivorBundle:Survivor:leave_camp }
    requirements:
        _methods:   POST
        survivor_id:    \d+
        camp_id:        \d+
        
#Assign a survivor to a camp
xali_survivor_management_assign_camp:
    path:   /{survivor_id}/assign_camp/{camp_id}
    defaults:   { _controller: XaliSurvivorBundle:Survivor:assign_camp }
    requirements:
        _methods:   POST
        survivor_id:    \d+
        camp_id:        \d+
        
#Search a survivor
xali_survivor_search_search:
    path:     /search
    defaults: { _controller: XaliSurvivorBundle:Survivor:search }