#Add a camp
xali_camp_management_add_camp:
    path:     /idorganisation/add_camp
    defaults: { _controller: XaliCampBundle:Camp:add_camp }

#See profile
xali_camp_profile:
    path:     /profile
    defaults: { _controller: XaliCampBundle:Camp:profile }
    
#Assign a volunteer to a camp
xali_camp_assign_volunteer:
    path:       /assign_volunteer
    defaults:   { _controller: XaliCampBundle:Camp:assign_volunteer }