#Add a camp for organisation which has id equals to {id}
xali_camp_management_add_camp:
    path:     /{id}/add_camp
    defaults: { _controller: XaliCampBundle:Camp:add_camp }
    requirements:
        id: \d+

#See camp's profile which has id equals to {id}
xali_camp_profile_profile:
    path:     /profile/{id}
    defaults: { _controller: XaliCampBundle:Camp:profile }
    requirements:
        id: \d+
    
#Assign a volunteer to a camp
xali_camp_management_assign_volunteer:
    path:       /{id}/assign_volunteer
    defaults:   { _controller: XaliCampBundle:Camp:assign_volunteer }
    requirements:
        id: \d+
        
#See camps, sorted by organisation
xali_camp_search_see_all:
    path:     /see_all/{organisation_id}
    defaults: { _controller: XaliCampBundle:Camp:see_all, organisation_id: 0 }
    requirements:
        organisation_id:    \d+

#Delete a camp
xali_camp_delete:
    path:  /delete/{id}
    defaults: { _controller: XaliCampBundle:Camp:delete }
    requirements:
        _method:  POST

#See volunteers who belong to a given camp
xali_camp_display_see_volunteers:
    path:   /{id}/see_volunteers
    defaults: { _controller: XaliCampBundle:Camp:see_volunteers }
    requirements:
        id: \d+
        
#See survivors who belong to a given camp
xali_camp_display_see_survivors:
    path:   /{id}/see_survivors
    defaults: { _controller: XaliCampBundle:Camp:see_survivors }
    requirements:
        id: \d+