<?php

namespace Xali\Bundle\SurvivorBundle\Entity;

/**
 * SurvivorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurvivorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find a survivor joined with its camp
     * 
     * @param integer $id the survivor's id
     * @return Xali\Bundle\SurvivorBundle\Entity\Survivor
     */
    public function findWithCamp($id)
    {
        return $this->createQueryBuilder('s')
                    ->leftJoin('s.camp', 'c')
                    ->addSelect('c')
                    ->where('s.id = :survivor_id')
                    ->setParameter('survivor_id', $id)
                    ->getQuery()
                    ->getOneOrNullResult()
                ;
    }
}
