<?php

namespace Xali\Bundle\SurvivorBundle\Entity;

/**
 * SurvivorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurvivorRepository extends \Doctrine\ORM\EntityRepository
{
}
