<?php

namespace Xali\Bundle\CampBundle\Entity;

/**
 * CampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count volunteers number in a given camp
     * 
     * @param Xali\Bundle\CampBundle\Entity\Camp $camp
     * @return integer
     * @author Anthony Bocci <boccianthony@yahoo.fr>
     */
    public function countVolunteersNb($camp)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        return $queryBuilder->select('COUNT(DISTINCT(u))')
                     ->from('XaliUserBundle:User', 'u')
                     ->where('u.camp = :camp')
                     ->setParameter('camp', $camp)
                     ->getQuery()
                     ->getSingleScalarResult()
            ;
    }

}
